apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-argocd-test
  namespace: teste
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-argocd-test
  template:
    metadata:
      labels:
        app: nginx-argocd-test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
